### ISSUE TITLE
It dosn't work.

### ISSUE THREAD

**Issue by yibie** [rougier/org-imenu#1]
My Emacs version 28.1, org-mode version 9.5.3, I use Mac OS 12.4.

My configure:

`(use-package org-imenu-filter
  :straight (org-imenu-filter
			 :host github
			 :repo "rougier/org-imenu"))
`

When =M-x org-imenu-filter-mode=, it dosn't show the minimap on the buffer right side.

**Comment by rougier** [comment]
Sorry, it's work in progress and it should work in a few hours hopefully.

**Comment by rougier** [comment]
Done.
